AllCops:
  Exclude:
    - vendor/**/*
    - Guardfile

AlignParameters:
  Enabled: false
ClassLength:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
Style/FileName:
  Enabled: false
Style/Alias:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
LineLength:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 200
PerceivedComplexity:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/CaseIndentation:
  Exclude:
    - attributes/*.rb
Lint/EndAlignment:
  Exclude:
    - attributes/*.rb
