name 'mineos'
maintainer 'Will Fisher'
maintainer_email 'will@tekofire.net'
license 'mit'
description 'Installs/Configures mineos'
long_description 'Installs/Configures mineos'
version '2.0.1'
issues_url 'https://github.com/teknofire/mineos-cookbook/issues'
source_url 'https://github.com/teknofire/mineos-cookbook'

supports 'ubuntu'
chef_version '~> 14'

depends 'java'
depends 'nodejs', '~> 5.0.0'
